language: c
sudo: required
dist: trusty
before_install:
- sudo apt-get install cpputest doxygen graphviz
script:
- cd $TRAVIS_BUILD_DIR
- autoconf
- ./configure
- make
- make test
- test/runtests
- make dist
- cd $TRAVIS_BUILD_DIR/src_docs
- doxygen doxygen.cfg
after_success:
- curl --upload-file *.tar.gz -u "$FTP_USER:$FTP_PASSWORD" $FTP_TARGET 
- cd $TRAVIS_BUILD_DIR/src_docs
- ./publish.sh
notifications:
  slack: hahnlab-cafe:qWd7TTjmDiENiF99zgek98Rr
